### ISSUE TITLE
Bug/Enhancement: Fix Tesla icons for permit/plan/construction to go to map.

### ISSUE THREAD

**Issue by Rovastar** [supercharge-info/supercharge.info#113]
Currently broken.

Change the URL for these too 
https://www.tesla.com/findus?location=teslasiteid
E.g.
https://www.tesla.com/findus?location=33720

This shortcut takes it too the tesla map location for the coming soon.

Maybe make the icon a little different

**Comment by paulkva** [comment]
Done as part of #116
