### ISSUE TITLE
Clicking to view details on a site's popup may get an error

### ISSUE THREAD

**Issue by Dani21** [supercharge-info/supercharge.info#119]
I refreshed the page after navigating to the pin, then clicked the pin and clicked details. The details link didn't respond. I wasn't able to reproduce it afterwards.

See a screenshot of the underlying error below:

![Source Trace](https://github.com/supercharge-info/supercharge.info/assets/1804643/21552122-3457-4fea-af03-ed7eb9653b4f)

**Comment by Dani21** [comment]
I was able to trigger a similar error but also couldn't reproduce it. I think these bugs have to do with using the direct link feature.

![Set Content Details Error](https://github.com/supercharge-info/supercharge.info/assets/1804643/25ff52bf-1541-4347-9fc8-74dd6f51b564)

**Comment by paulkva** [comment]
I reproduced the `toggleHistory` error locally and I think I now have a fix. I have a couple other small fixes in the works and hope to push them to our Dev server soon.

**Comment by paulkva** [comment]
#121 should fix this when merged. (Already deployed to Test, please try to reproduce it there if you have a chance.)
