### ISSUE TITLE
Add country names on the changes tab.

### ISSUE THREAD

**Issue by kdwink** [supercharge-info/supercharge.info#23]
> It's about time that you put the country name in the "changes" section. "Mississauga, ON" Should of course be "Mississauga, Canada" or "Mississauga, ON, Canada" "San Jose, CA" Ridiculous, put the country name in there. Either "San Jose, USA" or "San Jose, CA, USA". It can't be that hard. Also for China you should include the province. For example "Xi'an - Wanzhong International Plaza, China" should of course be "Xi'an - Wanzhong International Plaza, Shaanxi, China". Can't be that hard, why this ignorant error has been around for as long as it has is a mystery.\

LOL.  Programming takes time, mystery solved.  :-)   A very good suggestion though.

**Comment by kdwink** [comment]
> I would like it if you wrote the country for all superchargers. For some you just write a region/state. For example: "Saint-Romuald, QC" which should be "Saint-Romuald, Canada" or if you think regions are important then "Saint-Romuald, QC, Canada". The same goes for chargers in USA ("Greensboro, NC" should of course be "Greensboro, USA" or "Greensboro, NC, USA". And also Australia if I remember correctly. And if you continue to include regions/states then I would like to have the states written out for China (most important, unlike Australia and Canada which you could just use the country), France, Germany, Spain and which emirate in the United Arabs Emirate. Also for India, Brazil and Argentina once there are superchargers there. I would also prefer if you split up your supercharger grouping in statistics into the 7 continents that are clearly defined (unlike made up regions like "asia pacific" that depends on who you ask which countries are included). So Europe, North America, Asia and Oceania so far and South America, Africa added later (I doubt we will see chargers in the 7th continent Antarctica anytime soon, or maybe ever). Thank you! And also thank you for one awesome site that I've been visiting way too many times than what could be considered healthy. ;)

**Comment by paulkva** [comment]
When the changes in #91 reach production, you'll be able to see the full address, including country, of any site by hovering over its name. There has been a lot of discussion over time about including more info on the Changes page vs keeping it streamlined. With the additional complexity of Magic Dock and other manufacturers adopting NACS, along with increasing cases where not every stall at a site is equivalent (e.g. some are V2, some are V3), we're currently leaning toward keeping things as streamlined as possible. We will try to make it as easy as possible to get at more detailed info though.

**Comment by paulkva** [comment]
Got a good laugh at re-reading the initial request and Keith's response. I think #91 did in fact resolve this, so I'm closing the issue.
