### ISSUE TITLE
Indicate which supercharges have CCS support.

### ISSUE THREAD

**Issue by kdwink** [supercharge-info/supercharge.info#35]
> Now that it is confirmed that the Model 3 comes with CCS (in Europe and possible Australia/New Zeeland/South Korea) and Tesla has said that they will add another charging cable to the stalls it would be interesting and important to be able to see which locations have CCS and how many stalls that are converted.

**Comment by SeBsZ** [comment]
Hi @kdwink,
It would be fantastic to start keeping track of the conversion progress. It’s going faster than I anticipated. So far I’ve only heard of the Netherlands starting conversions. Here is a list of Superchargers that have just been converted so far (partially, a few stalls per Supercharger):
Badhoevedorp, NL
Oosterhout, NL
Zwolle, NL
Breda, NL

It would be great to be able to see the number of CCS/Type2 dual stalls per supercharger there are, and some graphs maybe of how many Superchargers in Europe are now Model 3 compatible.

**Comment by No0ne** [comment]
+1

**Comment by SeBsZ** [comment]
Eindhoven, NL
Zoetermeer, NL
and Zevenaar, NL

have now also been converted. I don't know about the ones in Norway that started a few days ago. If you need to know the exact number of stalls that are converted, I can get that information for you.

**Comment by SeBsZ** [comment]
@No0ne why is your spreadsheet no longer accessible

**Comment by paulkva** [comment]
I think we can close this as handled by #107.
