### ISSUE TITLE
Add Momentum scrolling for IOS

### ISSUE THREAD

**Issue by rakusan2** [supercharge-info/supercharge.info#36]
Currently, there is no momentum scrolling for WebKit implemented thereby making scrolling not continuous on any of the pages.

This can be fixed by adding `-webkit-overflow-scrolling: touch;` as shown on [ccs-tricks](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/)

If this is added, it will greatly improve the usability of this site on IOS.

**Comment by Dani21** [comment]
It looks like this is being provided via Bootstrap. Is there somewhere this isn't working?
