### ISSUE TITLE
Status icon for sites where additional stalls are being added.

### ISSUE THREAD

**Issue by kdwink** [supercharge-info/supercharge.info#4]

**Comment by paulkva** [comment]
This could be further generalized (or further split out!) to include partially open / partially closed sites. Related, it might also be worth adding a "notes" field for brief comments like "1A-1B offline since (X date)" or "Adding 4 more stalls"... not sure if that's worth tracking separately.

**Comment by paulkva** [comment]
We might want to combine this with #78, and I expect it will be at least partially implemented with the multi-connector work.

**Comment by paulkva** [comment]
Completed as part of PR #107
