### ISSUE TITLE
Email notification for site changes.

### ISSUE THREAD

**Issue by kdwink** [supercharge-info/supercharge.info#6]
On the user profile page allow users to enable email notification when a new site is opened.

Allow them to specify one of: 
(a) a specific region; or 
(b) a specific country;  or
(3) a radius from a specific location

**Comment by kdwink** [comment]
> I'd like to be able to register an email address, and a territory (UK in my case) and get email alert if there is any change to a supercharger in that territory. Thanks. Great product.

**Comment by kdwink** [comment]
> Any chance of adding a sign-up for notifications for changes? I would love to be notified if any additional I-80 Wyoming superchargers are added.

**Comment by kdwink** [comment]
> I'd love to be able to register my Email address to get notification of any updates to my "territory" - it would save me pressing REFRESH on the CHANGES page several times a day - 99% of the time that action is fruitless of course! Great product though, many thanks. Kris

**Comment by kdwink** [comment]
> Hello, I enter the website everyday to look for new updates on the supercharger map, and I think that it would be great if you could allow registered users to receive an e-mail when a change has been done in the supercharger map, in order to receive updates whithout having to go to the web every day. That could be very helpful! Thank you for the great job!! Lucky

**Comment by paulkva** [comment]
I think our answer here might be to follow via either RSS or Twitter, correct?

**Comment by paulkva** [comment]
Closing because following via rss/twitter should satisfy the request.
