### ISSUE TITLE
Update maximum range slider from 350 miles to 405 miles

### ISSUE THREAD

**Issue by Delvin4519** [supercharge-info/supercharge.info#73]
The maximum tesla range is 405 miles, but the range slider is capped at 350 miles, too short of the maximum tesla range.

Source file to change 1 line to reflect updated tesla distance for charging:

https://github.com/supercharge-info/supercharge.info/blob/master/src/main/primary_entry/script/page/map/RangeModel.js#L19

**Comment by paulkva** [comment]
Ready to test on http://pk.www.dev.supercharge.info:9090/map
